# Generated by Django 4.1.7 on 2023-03-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
